### ISSUE TITLE
module 'ticketevolution' has no attribute 'Api'

### ISSUE THREAD

**Issue by ElStone** [ticketevolution/ticketevolution-python#4]
Getting AttributeError: module 'ticketevolution' has no attribute 'Api' when trying to test the package.  I'm running python 3.7.   Any idea as to why?

**Comment by coneybeare** [comment]
Thanks for commenting @ElStone . Unfortunately, this python library has been deprecated a long time ago, yet we failed to remove it from the public. While aspects of it may work, I highly encourage you to engage with the API directly: https://developer.ticketevolution.com/
